name: finabm
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - numpy>=1.23,<2.0
  - scipy>=1.10,<2.0
  - pandas>=1.5,<2.0
  - matplotlib>=3.7
  - tqdm>=4.64
  - pqdm>=0.1
  - openpyxl
  - jupyterlab
  - ipywidgets
